### ISSUE TITLE
HTML Provider doesn't work with FSI with F# 4.6

### ISSUE THREAD

**Issue by leolorenzoluis** [fsprojects/FSharp.TypeProviders.SDK#318]
### Description

Running load on HTML Provider will throw an exception with FSI F# 4.6

### Repro steps

```

type NasdaqCompaniesByName = HtmlProvider<"https://www.nasdaq.com/screening/companies-by-name.aspx">
NasdaqCompaniesByName.Load("https://www.nasdaq.com/screening/companies-by-name.aspx?letter=A")

```
### Expected behavior

It should not throw exception

### Actual behavior

>error FS3033: The type provider 'ProviderImplementation.HtmlProvider' reported an error in the context of provided type 'FSharp.Data.HtmlProvider,Sample="https://www.nasdaq.com/screening/companies-by-name.aspx"', member 'Load'. The error: assembly mscorlib not found

### Known workarounds

Run it with dotnet cli and not through FSI

### Related information 

* Operating system OSX
* Branch latest
* .NET Runtime, CoreCLR or Mono Version .NET Core SDK 2.2.300

**Comment by dsyme** [comment]
This has been fixed since then, and would go to FSharp.Data repository in any case
